# Generated by Django 5.0.2 on 2024-03-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clips',
            name='category',
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='game_categories')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.game')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentClips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clips')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='clips',
            field=models.ManyToManyField(through='user.TournamentClips', to='user.clips'),
        ),
    ]
