# Generated by Django 5.0.2 on 2024-03-25 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_clips_category_tournamentclips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_participants',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)]),
            preserve_default=False,
        ),
    ]
