# Generated by Django 5.0.2 on 2024-03-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_gamecategory_game_game_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
    ]
